### ISSUE TITLE
git addでステージングしたファイルの一部をアンステージング(キャンセル)したい

### ISSUE THREAD

**Issue by okiyuki99** [okiyuki99/HowToGit#5]
#### 手順

ファイルをキャンセルする場合 : `git rm --cached ファイル名`
ディレクトリをキャンセルする場合: `git rm -r --cached ディレクトリ名`

#### 参考
- 2010-09-16 git addでステージングしたファイルをアンステージング(キャンセル)する : http://d.hatena.ne.jp/mrgoofy33/20100910/1284068244

**Comment by gingi99** [comment]
#### 手順2 :  ``` $ git reset HEAD [filename] ```

#### 参考
- 2010-11-16 git addの取り消しと、コミット済みのファイルを除外する方法: http://d.hatena.ne.jp/kanonji/20101116/1289885277

#### rm --cached の違いは？

ぐぐる
